### ISSUE TITLE
Q & A

### ISSUE THREAD

**Issue by drwelby** [stac-extensions/classification#1]
### Questions I have or have seen others ask:

- Are these Asset level only?
- Can classification be used to describe a field in vector or tabular asset?
- Classifications in one or more bands or fields?
- Use as a colormap?
- Handling ranges?

**Comment by drwelby** [comment]
### Currently using:
- Microsoft Planetary Computer
  - For classification
  - https://planetarycomputer.microsoft.com/api/stac/v1/collections/gap
  - 
### Waiting for a spec:
- Maxar ARD (me)
- Planet UDM (https://github.com/stactools-packages/planet/issues/3)

**Comment by drwelby** [comment]
@cholmes can you provide the best example of a UDM STAC that I can use for reference?

**Comment by cholmes** [comment]
I've never actually got to making a STAC version, it's just been on the list to try out. But you can get a sense of the fields we'll want at: https://developers.planet.com/docs/data/udm-2/

Right now it's one band per classification, but the core classifications are actually mutually exclusive, so we have an internal process that collapses them into a single band, and so I may try to use that if we make a STAC version of the data.

If you want to see a STAC Item that includes the UDM you can check out https://www.planet.com/data/stac/open-skysat-data/20201211_223832_ssc4_u0001/20201211_223832_ssc4_u0001.json but I don't know that it's all that helpful. But you can get the UDM https://storage.googleapis.com/open-cogs/planet-stac/20201211_223832_ssc4_u0001/20201211_223832_ssc4_u0001_udm2.tif

**Comment by pjhartzell** [comment]
@drwelby I put together a few examples based on what I've been able to glean from this repo and links to external resources: https://gist.github.com/pjhartzell/2dff391f9787ab6c649d5961364a2118

As mentioned on the STAC call today, we are interested in getting bitmask information into the classification extension. I have some hours this week to devote to this, so happy to discuss/help/whatever.

**Comment by drwelby** [comment]
@pjhartzell Great, thanks! I'll give it look tomorrow.

**Comment by pjhartzell** [comment]
Will we provide something like `classification:classes` with a type of `[string]` for summarizing classes in Item `properties` or Collection `summaries`? 

There are several examples where `label:classes` from the Label Extension is used for this, but it would seem that we would want to provide a complete solution here.

**Comment by pjhartzell** [comment]
Also noting that `classification:classes` is very close to the current `classification:classed` term. Perhaps change to `classification:categorical`?

**Comment by m-mohr** [comment]
I think I've extracted all open questions into separate issues.
