### ISSUE TITLE
Ambiguous bitmask terminology

### ISSUE THREAD

**Issue by pjhartzell** [stac-extensions/classification#11]
Suggestion to change `classification:bitmask` to `classification:bitmask_parts` to further clarify that we do not want straight bitmask values. 

Side benefit is that it mirrors the `classification:classes` and `Class` object, i.e, we will have `classification:bitmask_parts` and a `Bitmask_Part` object.

In other words, we want to be clear that the intent is for `value`s like this (bitmask parts generated by a bit shift and bitmask)
```
"classification:bitmask_parts": [
{
    "description": "cloud confidence",
    "bits": [
        8,
        9
    ],
    "classes": [
        {
            "value": 0,
            "description": "no confidence level set"
        },
        {
            "value": 1,
            "description": "low confidence"
        },
        {
            "value": 2,
            "description": "medium confidence"
        },
        {
            "value": 3,
            "description": "high confidence"
        }
    ]
}
```

And not straight bitmask values, which would result in `value`s like this:
```
"classification:bitmask": [
{
    "description": "cloud confidence",
    "bits": [
        8,
        9
    ],
    "classes": [
        {
            "value": 0,
            "description": "no confidence level set"
        },
        {
            "value": 256,
            "description": "low confidence"
        },
        {
            "value": 512,
            "description": "medium confidence"
        },
        {
            "value": 768,
            "description": "high confidence"
        }
    ]
}
```

I am also seeing the value in [gee](https://github.com/radiantearth/stac-spec/issues/977#issuecomment-775176807)'s use of `first_bit` and `bit_count` instead of our current `bits` list. This prevents abuse by doing something like `"bits": [0, 8, 9]`, which is more appropriate to generating pixel values with a straight bitmask.

**Comment by drwelby** [comment]
Do we then want `classification:bitmask` for straight bitmasks? Do we know of a good example of one?

**Comment by pjhartzell** [comment]
I don't have a great example. I think you would want to switch to `classification:classes` if you are generating actual pixel values from bitmasks. Unless there is some intermediate use of a straight bitmask that only partially defines a pixel value. But not sure why you would want to do that.

**Comment by pjhartzell** [comment]
Summarizing proposed edits here again for clarity.

**Terminology changes. One of:**
1. `classification:bitmask` --> `classification:bitmask_parts` and `BitRange` Object --> `BitmaskPart` Object; or
2. `classification:bitmask` --> `classification:bitrange` and keep `BitRange` Object

I'm leaning toward the latter option.

**BitRange (potentially renamed to BitmaskPart) Object field changes**
1. Replace `bits` with `first_bit` and `bit_count`.

Open to different terminology.

**Comment by pjhartzell** [comment]
@drwelby I'm not 100% on your meaning. You are correct that a bitmask can use parts/ranges. You can specify whatever bits you want to mask via the `bits` list, e.g, [0], [0,1], [1,3,4,8], whatever. 

But the data we are describing with the extension is often described as a "bit index" or "bit flags". These flags are always at a single bit location or at multiple adjacent bits. And you don't apply a straight bitmask to get the values of these flags. You shift the bits by the first bit index value and then apply a mask the same length as the number of bits in the flag. 

Just looking to make things clear with the terminology, i.e., don't imply a straight bitmask if that is not what is being described in the extension. But I think most users will look in the examples directory to confirm how things work, so the terminology and how the bit indices are stored may not be critical.

Given the number of words above, maybe there is a better way to represent things?

**Comment by drwelby** [comment]
The question is more about whether anyone actually uses straight bitmasks.

However, I see your point about terminology, and since this is mostly going to be used right now for Landsat, I think we use that and call it `classification:bitindex` and then keep the `BitRange` object. 

Looking at other Repo I think we can call the ranges in the table `Bit Range`,  since we don't seem to use that name as keys.

**Comment by pjhartzell** [comment]
>The question is more about whether anyone actually uses straight bitmasks.

Ah. OK. Yeah, I don't know. 

>Looking at other Repo I think we can call the ranges in the table Bit Range, since we don't seem to use that name as keys.

 Is this just confirming to keep the name of the `BitRange` object the same?

**Comment by pjhartzell** [comment]
Potentially looking at something like this:
```
"classification:bitindex": [
    {
        "description": "no data",
        "first_bit": 0,
        "bit_count": 1,
        "classes": [
            {
                "value": 0,
                "description": "no data in pixel"
            },
            {
                "value": 1,
                "description": "data in pixel"
            }
        ]
    },
    {
        "description": "cloud confidence",
        "first_bit": 8,
        "bit_count": 2,
        "classes": [
            {
                "value": 0,
                "description": "no confidence level set"
            },
            {
                "value": 1,
                "description": "low confidence"
            },
            {
                "value": 2,
                "description": "medium confidence"
            },
            {
                "value": 3,
                "description": "high confidence"
            }
        ]
    }
]
```

**Comment by Kirill888** [comment]
@pjhartzell 
I think there are two ways to look at the problem and depending on the use case different representations fit better.

1. Bit packing small "enumeration" values
2. Dealing with actual bitmasks

For bit packed enumeration values (1), bit range representation as described in a comment above makes most sense: you need to know what part of the value you need to extract `(x>>first_bit)&all_ones(bit_count)` and then you need a description of all the possible values encoded in that part.

For dealing with actual bitmask data (2) this only works when describing individual bits, but will not work for defining more complex, multi-bit masks. So if you have, say `cloud=1|no_cloud=0` and `data=0|no_data=1` and they are not adjacent you will be able to describe those bits separately, but you won't be able to define `data and no_cloud` bitmask. The representation that works for this case is `arbitrary bit selection` + `value`. Coming back to the example, let's say cloud bit is bit 7 and nodata is bit 0.

```
7654_3210
|||| ||||
0XXX_XXX0 -- clear pixel
1XXX_XXX0 -- cloud pixel
XXXX_XXX0 -- some valid pixel, could be cloud
XXXX_XXX1 -- nodata pixel
0X01_0110 -- clear pixel classified as `0_1011` (pasture)
```

Representation that works for this case:
- bits that should be kept unchanged (the rest a pulled down to 0)
- description of possible values formed after pulling down irrelevant bits to 0

I think for STAC case it should be enough to just describe all the bits and bit-packed enumeration types, and I think it's reasonable to assume that bit-packed small integers are stored sequentially. Combinations of those bits, even if really common ones like `valid+clear` can then be worked out outside of STAC spec.

**Comment by pjhartzell** [comment]
Excellent summary. Thanks @Kirill888. 

>I think for STAC case it should be enough to just describe all the bits and bit-packed enumeration types, and I think it's reasonable to assume that bit-packed small integers are stored sequentially. Combinations of those bits, even if really common ones like valid+clear can then be worked out outside of STAC spec.

This is where we've been trending. Idea being to limit STAC to describing the bit-packed enumerations, and any combinations that require actual bitmasks to be handled by users. STAC provides the metadata, the user decides what to do with it (e.g., create custom bitmasks).

**Comment by pjhartzell** [comment]
>...I think it's reasonable to assume that bit-packed small integers are stored sequentially.

As someone who consumes this type of data, would you prefer/recommend a more flexible option than `"first_bit": val` and `"bit_count": val`? We initially were using `"bits": [val, val, ...]`, which does not enforce sequential storage. I was leaning away from this to specifically prevent combinations of different flags/enumerations.

**Comment by drwelby** [comment]
> So if you have, say `cloud=1|no_cloud=0` and `data=0|no_data=1` and they are not adjacent you will be able to describe those bits separately, but you won't be able to define `data and no_cloud` bitmask

@Kirill888 in this case, isn't `nodata` and `no_cloud` two different classes? It seems like the decision to combine them is up to the end user. I would hope no one is encoding a single class across non-sequential bits.

**Comment by pjhartzell** [comment]
>So I guess the question really comes down to: do we avoid the word bitmask even though it's commonly used to describe a bit index? Or do we just use it since it's unlikely that any metadata would have true bitmask implementations?

Should we avoid `bitmask` in case it is needed in the future for a true bitmask? `bitindex` is OK. Maybe `bitrange`? Although, that overlaps the name of the BitRange Object.

**Comment by drwelby** [comment]
I'm seeing https://en.wikipedia.org/wiki/Bit_field as a close fit, but since https://www.usgs.gov/landsat-missions/landsat-collection-2-quality-assessment-bands labels them all as `bit index` and I assume this will be the first and primary use of this STAC extension, let's go with that.

**Comment by pjhartzell** [comment]
Yeah, the unit is designated as `bit index` in the landsat docs. I do like `bitfield`, though. 🙂

**Comment by drwelby** [comment]
`bitfield` has a nice ring to it.

**Comment by pjhartzell** [comment]
`bitfield` or `bitfields`? I think `bitfields`, no?

**Comment by drwelby** [comment]
Let's see how it looks: 

`classification:bitfields`

Looks pretty good.

By the way, how urgent are you for this spec?

**Comment by pjhartzell** [comment]
Yeah, let's go with `bitfields`. Does it also make sense to also change the name of the `BitRange` object to `BitField` (or `Bitfield`)? That way `classification:bitfields` is logically comprised of a list of `BitField` objects?

>By the way, how urgent are you for this spec?

If we could wrap it up by end of next week, that would be great.

**Comment by drwelby** [comment]
> That way `classification:bitfields` is logically comprised of a list of `BitField` objects?

I'm leaning towards this but will let it stew over the weekend.

**Comment by Kirill888** [comment]
To me at least (done C++ and embedded dev work in the past) `bit mask` implies that it only contains boolean flags, so it's a specialization of `bit field` where all members have width of 1 bit exactly. I think `BitField` name makes most sense here. You can define it as a contiguous bit range, for that `offset+size` makes more sense to me than `in:out`/`start:stop`, since with `in:out` there is always confusion of inclusive vs exclusive range.

Here is an example of [bit_field](https://en.cppreference.com/w/cpp/language/bit_field) notation used in C++, there they don't use offsets, only lengths of each field, including "skipped" fields, as this avoids possibility of overlapping values.

**Comment by pjhartzell** [comment]
I'm fine with either set of terms.

**Comment by drwelby** [comment]
OK, just to double-check we're all on the same page here. Let's say we're interested in these two bits:

`00000XX0`

This would be `offset:1`, `length:2` and to extract them you would

- right-shift by `offset` (`data >> 1`) to get `000000XX`
- left-shift 1 `length` times to get `00000011` (given by `1<<length - 1`)
- AND these two values to get the value we will store in `value`

**Comment by pjhartzell** [comment]
Looks good. Might be worth documenting something like this for users. 

To make sure I'm clear on the above, I think we need  parentheses in the mask creation to enforce the desired order of operations:  
- Based on order of operation, `1<<size - 1` is the same as `1<<(size - 1)`, which equates to `00000010` (for `size=2`), which is not what we want.
- `(1<<size) - 1` equates to `00000011`, which is the mask we want

**Comment by pjhartzell** [comment]
I think we are about done. Example of current form, using all fields except `color-hint` in the `Class` objects:
```
"classification:bitfields": [
    {
        "name": "no_data",
        "description": "no data mask",
        "roles": [
            "nodata"
        ],
        "offset": 0,
        "size": 1,
        "classes": [
            {
                "name": "no_data",
                "description": "no data in pixel",
                "value": 0
            },
            {
                "name": "data",
                "description": "data in pixel",
                "value": 1
            }
        ]
    },
    {
        "name": "cloud_confidence",
        "description": "cloud confidence levels",
        "roles": [
            "cloud"
        ],
        "offset": 8,
        "size": 2,
        "classes": [
            {
                "name": "none",
                "description": "no confidence level set",
                "value": 0
            },
            {
                "name": "low",
                "description": "low confidence",
                "value": 1
            },
            {
                "name": "medium",
                "description": "medium confidence",
                "value": 2
            },
            {
                "name": "high",
                "description": "high confidence",
                "value": 3
            }
        ]
    }
]
```
