### ISSUE TITLE
Human readable color names in addition to hex

### ISSUE THREAD

**Issue by schwehr** [stac-extensions/classification#12]
A topic that overlaps with the already closed #3 that can spawn endless bikeshedding, but...

Any chance for allowing human readable color names in the `color` field?

e.g. https://developers.google.com/earth-engine/guides/image_visualization#color-palettes

- https://en.wikipedia.org/wiki/Web_colors
- https://www.w3.org/wiki/CSS/Properties/color/keywords
- https://www.w3.org/TR/CSS21/syndata.html#color-units

And just to mix things up a bit, color palettes... e.g,

- https://github.com/gee-community/ee-palettes
- https://docs.generic-mapping-tools.org/dev/cookbook/cpts.html

**Comment by m-mohr** [comment]
I don't really like those names because in the end you always need a long "name to code" list in the dependency tree to covert back. I think I'd prefer to not complicate too much here.
