### ISSUE TITLE
Collection level representation

### ISSUE THREAD

**Issue by drwelby** [stac-extensions/classification#16]
Not sure where/how to put classes this in a Collection so that it can be applied to child items. Is it part of `summary` information or in a different extension?

**Comment by pjhartzell** [comment]
`classification:classes` with a list of all Class Objects used in the child Items should be able to be included in Collection `summaries`, no? 

The classes would also be contained in the `item-assets` extension, if that was used. 

This topic was discussed in #4 as well.
