### ISSUE TITLE
eo:bands versus raster:bands

### ISSUE THREAD

**Issue by drwelby** [stac-extensions/classification#17]
`eo:bands` versus `raster:bands`: is there a distinction that would make it not appropriate to put class information in one of their `band ` objects?

**Comment by pjhartzell** [comment]
Class information doesn't really fit in `eo:bands`, does it? Per the Extension spec verbiage, `eo:bands` is used to describe the available spectral bands in an Asset. Classification rasters don't seem to fit that. Whereas `raster:bands` is not specific to spectral data.

You can always add `raster:bands` to an Asset that includes `eo:bands`, so you can include classification information for spectral data if desired (via a range object for the class `value`, I guess).

**Comment by drwelby** [comment]
OK, it seemed redundant to have two ordered "band-stuff" objects but it makes sense and is easy enough to explain.
