### ISSUE TITLE
Road Map

### ISSUE THREAD

**Issue by drwelby** [stac-extensions/classification#18]
## 0.0.1 core version: Late March

- rasters only
- integer values only

### Pending Enhancements:

- coordinate with Table extension for data dictionary use, allow strings as values
- coordinate with Label/Vector-Label extensions for alignment
- consider allowing classifications to be defined via range or array values

### Pilot implementation

- Planetary Computer: ASAP
- Maxar ARD: May 2022
- Planet UDM: TBD

**Comment by pjhartzell** [comment]
Looks good. I'll generate an example Landsat item that uses `classification:bitfields`.

**Comment by drwelby** [comment]
@pjhartzell anything else you want to do with this? I think we are ready to call this 1.0.0. I'll update the changelog to reflect that.

**Comment by pjhartzell** [comment]
I'm good for 1.0.0. I'll add a collection example for bitfields in the near future, but that I don't see why that should hold us back.

**Comment by pjhartzell** [comment]
@drwelby What are next steps? Is the PR ready for review for a merge into main?

**Comment by drwelby** [comment]
I'm ready to merge to main and announce it, unless you want to hold it in the PR stage for last minute feedback. I'll announce either status on Gitter and in the Stac Extensions issues.

**Comment by pjhartzell** [comment]
Go ahead and merge. 🙂

**Comment by m-mohr** [comment]
What's the status of this issue?

**Comment by drwelby** [comment]
Stale, we can close
