### ISSUE TITLE
Allow lowercase letters in color-hint

### ISSUE THREAD

**Issue by gadomski** [stac-extensions/classification#26]
Currently only uppercase are allowed: https://github.com/stac-extensions/classification/blob/main/json-schema/schema.json#L165. This seems needlessly restrictive.

**Comment by drwelby** [comment]
Thanks for spotting that, fixed in [047dfcc](https://github.com/stac-extensions/classification/commit/047dfcc92069afcd4f9559feaffc743b7b528e1f)
