### ISSUE TITLE
color-hint => color_hint

### ISSUE THREAD

**Issue by m-mohr** [stac-extensions/classification#27]
In STAC we usually use snake_case for fields. Here, we did use color-hint instead of color_hint and I'd propose to change this so that tooling that relies on a certain set of characters don't get confused ;-)

**Comment by drwelby** [comment]
Thanks, fixed in v1.1.0

**Comment by gadomski** [comment]
Isn't this technically a breaking change?

**Comment by drwelby** [comment]
Technically yes but at this pilot stage and limited if any implementation it felt odd to call this 2.0.0.

I'm fine with changing the version number to be semantically correct if you prefer.

**Comment by gadomski** [comment]
Doesn't really affect me personally so I'm 🤷🏽, I was just curious if it had been considered. IMO if this is the policy, it'd be good to (a) document as such (e.g. on the readme) and (b) set some sort timeline for when we do hope to stabilize and commit to stricter versioning.

**Comment by drwelby** [comment]
For sure, the README says the extension is a "pilot", though I don't how well yet the concept of "maturity" overlaps with semver. I'm not sure if anyone has implemented this extension in the wild - even us (Maxar) have not put it into production yet.

So I think the game plan is to see this actually get used to the point we can agree it's stable, then take it out of "pilot" in say 6 months or so.

**Comment by gadomski** [comment]
> For sure, the README says the extension is a "pilot", though I don't how well yet the concept of "maturity" overlaps with semver.

Yeah, I don't know how well its defined myself. IMO `pilot` seems to line up better with a `v0.X.Y` series but that ship has sailed :-).

>  I'm not sure if anyone has implemented this extension in the wild - even us (Maxar) have not put it into production yet.

We're using it on the PC.

> So I think the game plan is to see this actually get used to the point we can agree it's stable, then take it out of "pilot" in say 6 months or so.

👍🏽
