### ISSUE TITLE
Rendering 

### ISSUE THREAD

**Issue by drwelby** [stac-extensions/classification#3]
Place to dump discussion of color representation and rendering

**Comment by drwelby** [comment]
Initially I was against any styling information in classification metadata, following the idea of separation of structure and presentation.

However, recently in working with ingesting STAC to output QGIS layer files, I realized that absent styling information layer objects will use default palettes. This means that different classes in different assets can look identical, as well as common associations (blue for water) can end up being used for "dry" classes.

But if we wander too far into styling we will get lost with just the variations in defining fills versus outlines, opacity, etc. So I think to keep things simple and explicit, we should just have `color`, or possibly even `color-hint`, defined as _"A reasonable color for rendering the data. This color defines the point, line, or pixel color, and for polygons defines the fill"_.

**Comment by cholmes** [comment]
I think I like the idea of `color-hint`, to help make it clear we're not endorsing this as 'real' styling. More like 'if there's not any style information then this is a good thing to use'.

**Comment by cholmes** [comment]
I agree with @m-mohr that we describe links to one solid json one that we recommend. If there's not a great single candidate then perhaps to 2 or 3. I think mapbox gl style is the leading json one... I've not actually used it much though.

**Comment by m-mohr** [comment]
I think this is reasonably defined now, I updated the description a bit by including the proposal from @drwelby ...
