### ISSUE TITLE
Revisions (post-draft)

### ISSUE THREAD

**Issue by drwelby** [stac-extensions/classification#4]
@pjhartzell

_see `rev-01` branch_

So far:

- added `classification:classes` to hold a summary of class names, similar to `label:classes['classes']`.
- renamed `classification:classes` to `classification:categorical` to make room for above and use the word "class" less.

Needing discussion/eyes: 
- bitmask structure

**Comment by drwelby** [comment]
I'm not 100% on "categorical"

_Maybe_ something like `bandmask`?

Something about it being singular?

**Comment by pjhartzell** [comment]
> Needing discussion/eyes:
> 
> * bitmask structure

I'm OK with the bitmask structure. I'll run it by Matt Hanson for another set of eyes.

**Comment by drwelby** [comment]
We could push `role` up one level if we're OK with having roles in bands.

**Comment by drwelby** [comment]
Latest push tries out `class_list` and `classes`, also thinking `Bitmask` should use `Bitmask_Part` or maybe `Bitmask_Range`

Do you have an example of a use case for `:class_list` that wouldn't be able to use `:classes`?

**Comment by m-mohr** [comment]
I don't really get the issues you are discussing here. Could you maybe elaborate with examples? e.g. what is the class_list useful for?

**Comment by pjhartzell** [comment]
Was thinking that `:class_list` would be something to go in a Collection `summaries` field and would just show the class names or descriptions (no values), similar to `label:classes`. But, yeah, maybe this isn't necessary.

**Comment by m-mohr** [comment]
Hmm, you could simply summarize the whole list of classes in Collection summaries.

**Comment by pjhartzell** [comment]
Correct. More of a presentation thing. Are the values relevant when you are just looking at classes exist?

**Comment by pjhartzell** [comment]
Something like this:
```
"label:classes": [
      {
        "classes": [
          "Background",
          "Unclassified (Cloud, Shadow, etc)",
          "High Intensity Developed",
          "Medium Intensity Developed",
          "Low Intensity Developed",
          "Developed Open Space",
          "Cultivated Land",
```

versus this:
```
"file:values": [
        {
          "values": [
            0
          ],
          "summary": "Background"
        },
        {
          "values": [
            1
          ],
          "summary": "Unclassified (Cloud, Shadow, etc)"
        },
        {
          "values": [
            2
          ],
          "summary": "High Intensity Developed"
        },
```

**Comment by m-mohr** [comment]
Sounds like a client thing to me... having all details is good and then clients can simplify the view. Also, you don't necessarily need to add the values to your summaries, if you don't want that. It's still a bit verbose though, agreed.

**Comment by pjhartzell** [comment]
Agreed. It shouldn't be required at the Item level. Optional for Items and Collections.

**Comment by m-mohr** [comment]
> It shouldn't be required at the Item level. Optional for Items and Collections.

I don't understand this... can you elaborate? Collection summaries are generated from items, so you don't need to define a field for collections specifically. And Item != Items?

**Comment by pjhartzell** [comment]
@m-mohr Yep, you're right. I wasn't thinking about it correctly. 

But if my understanding is improving, I think you are pointing out that we can eliminate `classification:class_list` and list all item class objects in the collection summaries using `classification:classes`. This gets rid of the requirement for repetitive information in each item.

**Comment by m-mohr** [comment]
Yes, that's correct.

**Comment by m-mohr** [comment]
Seems all be solved, great! :-)
