### ISSUE TITLE
Classification, File and Label extension overlap

### ISSUE THREAD

**Issue by KennSmithDS** [stac-extensions/classification#41]
Should the classification extension take precedence over the [file extension](https://github.com/stac-extensions/file) in terms of storing the classification values for label assets? 

I find that the `MappingObject` of `file:values` ([here](https://github.com/stac-extensions/file#mapping-object)) has significant overlap with the `ClassObject` of `classification:classes` [here](https://github.com/stac-extensions/classification#class-object) as well as the `ClassObject` of `label:classes` property from the label extension ([here](https://github.com/stac-extensions/label#class-object)) are to be used. The redundancy across the different specifications is confusing.

**Comment by drwelby** [comment]
We plan to deprecate the mapping values in `file`, see https://github.com/stac-extensions/file/issues/6
