### ISSUE TITLE
The required fields of class object are contradicted between the schema in the repo and the schema pointed by extension id

### ISSUE THREAD

**Issue by chorng** [stac-extensions/classification#46]
In the [repository](https://github.com/stac-extensions/classification/blob/main/json-schema/schema.json#L157) the required fields are `value` and `name`, but the schema pointed by [extension id](https://stac-extensions.github.io/classification/v1.1.0/schema.json) are `value` and `description`.

**Comment by drwelby** [comment]
@m-mohr how does this repo get converted to the github.io content?

**Comment by m-mohr** [comment]
@chorng The repo is the draft version (required: value, name), the released version version 1.1.0 requires value, description. Both the released version and the draft version are consistent, but you need to look at the same version. If you mix them they are inconsistent. So we are waiting for 2.0.0, see #42.

@drwelby I don't unserstand the question. I'm also not sure how it relates to the original issue?

**Comment by drwelby** [comment]
I couldn't figure out why they were out of sync, didn't catch the "draft" part.

**Comment by chorng** [comment]
@m-mohr Sorry if I misunderstood. The readme file in this repo points to [v1.1.0](https://github.com/stac-extensions/classification#classification-extension-specification) and the required fields of [class object](https://github.com/stac-extensions/classification#class-object) are name and value. Follow the schema linked in the readme the [$id](https://github.com/stac-extensions/classification/blob/main/json-schema/schema.json#L3) of the schema also points to v1.1.0 and the required fields of [class object](https://github.com/stac-extensions/classification/blob/main/json-schema/schema.json#L154) are value and name.

I think either the required fields need to be updated, or the extension id needs to point to v1.0.0 (or draft). Otherwise, it is confusing as the [released schema](https://stac-extensions.github.io/classification/v1.1.0/schema.json#) and the [draft schema](https://github.com/stac-extensions/classification/blob/main/json-schema/schema.json#) share the same $id but the required fields of the class object are different.

**Comment by m-mohr** [comment]
@chorng Yeah, that's how it is. The GH master could always be a draft. You need to look at https://github.com/stac-extensions/classification/tree/v1.1.0 for consistent documentation + schema. Ideally someone could work on releasing 2.0.0, but that's up to the community to push forward.
