### ISSUE TITLE
Add JSON Schema

### ISSUE THREAD

**Issue by m-mohr** [stac-extensions/classification#7]

**Comment by drwelby** [comment]
Do you have a preferred tool for writing schemas? I can start writing the schema files.

**Comment by pjhartzell** [comment]
I will take a stab at this this afternoon.

**Comment by m-mohr** [comment]
I'm not sure whether the template here is the latest version, so make sure to update it if required: https://github.com/stac-extensions/template/blob/main/json-schema/schema.json

**Comment by pjhartzell** [comment]
I opened a PR with a new schema on the [0.0.1-core](https://github.com/stac-extensions/classification/tree/0.0.1-core) branch.

**Comment by drwelby** [comment]
@pjhartzell It's not passing in the lint GH Action, are you able to see the results?

**Comment by pjhartzell** [comment]
Yep, I see the problems. Working on it.
