### ISSUE TITLE
Create an example that is valid STAC

### ISSUE THREAD

**Issue by m-mohr** [stac-extensions/classification#8]
... and that is ideally not part of eo:bands.

Also, we can create examples based on the following:

### Currently using:
- Microsoft Planetary Computer (@lossyrob ?)
  - For classification
  - https://planetarycomputer.microsoft.com/api/stac/v1/collections/gap
  - uses `file:values` for mapping and Label extension for class name list

- Google Earth Engine (@schwehr ?)
  - custom `gee` extension
  - see https://github.com/radiantearth/stac-spec/issues/977#issuecomment-775176807

### Waiting for a spec:
- Maxar ARD (@drwelby)
- Planet UDM (https://github.com/stactools-packages/planet/issues/3) (@cholmes)
- CARD4L extension (@m-mohr)

_Originally posted by @drwelby in https://github.com/stac-extensions/classification/issues/1#issuecomment-932489887_

**Comment by schwehr** [comment]
Hey, Sorry I missed this discussion in the prior locations.  It would be great to move the the `gee:` specific fields to standard fields.  I will try to look over the spec and see about examples.

**Comment by drwelby** [comment]
@schwehr We may adopt the `gee:` convention of `start_bit` and such instead of a list of bit positions, see end of [this comment](https://github.com/stac-extensions/classification/issues/11#issue-1172424459)
